# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0003_auto_20170618_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='countChild',
            field=models.CharField(default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='dateStart',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 11, 47, 44, 883362, tzinfo=utc)),
        ),
    ]
