# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nalog', '0004_auto_20170618_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userresults',
            name='IDuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='dateStart',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 15, 36, 26, 769805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
