# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0005_auto_20170618_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='checkChild',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='checkInv',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='countChild',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='dateStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='per13',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='per13div',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='per30',
            field=models.BooleanField(),
        ),
    ]
